version: '3'
services:
  php-fpm:
    hostname: app1
    image: php:8.3-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./:/var/www/html
    networks:
      - servercaddy_net
    ports:
      - "9000:9000"
networks:
  servercaddy_net:
    external: true