services:
  php_ssd:
    hostname: ssd
    build: docker/php/.
    image: php_ssd:fpm-alpine
    container_name: php_ssd
    restart: unless-stopped
    environment:
      TZ: Europe/Amsterdam
    volumes:
      - ./:/var/www/html
    networks:
      - docker_server_caddy

networks:
  docker_server_caddy:
    external: true