version: '3.8'

services:
  php_ssd:
    hostname: ssd
    build: docker/php/.
    image: php_ssd:fpm-alpine
    container_name: php_ssd
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - docker_server_caddy
    ports:
      - "${HTTP_PORT}:9000"

networks:
  docker_server_caddy:
    external: true