services:
  php_ssd:
    hostname: ssd
    build: docker/php/.
    image: php_ssd:fpm-alpine
    container_name: php_ssd
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./composer.json:/var/www/html/public/composer.json # Mount composer.json to public directory for WhatIsWhere app
    networks:
      - docker_server_caddy

networks:
  docker_server_caddy:
    external: true